[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar build/libs/demo-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[environments.production]
variables = { SPRING_PROFILES_ACTIVE = "production" } 