[build]builder = "dockerfile"

[deploy]
startCommand = "java $JAVA_OPTS -jar app.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[environments.production]
variables = { SPRING_PROFILES_ACTIVE = "production" } 