[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[environments.production]
variables = { SPRING_PROFILES_ACTIVE = "production" } 